version: 0.1
log:
  level: info
  fields:
    service: registry
    environment: mac
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: registry
http:
    addr: 0.0.0.0:5000
    secret: mytokensecret 
    debug:
        addr: localhost:5001
